version: '2'

services:
  mongo:
    image: mongo
    ports:
    - 27017:27017
  backend:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      - DB_HOST=mongodb://mongo/
      - DB_NAME=prod_db
      # - PORT=3000
      # - ADMIN_NAME=adminName
      # - ADMIN_LOGIN=admin
      # - ADMIN_PASSWORD=password
      # - SECRET=secrets
      # - SALT_ROUND=10